name: Deploy Lambda and API Gateway

on:
  push:
    branches:
      - feature/backend-health

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Prepare Lambda zip
        run: |
          cd lambda
          zip -r ../lambda.zip handler.py model_temp.json model_class.json
          cd ..

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2

      - name: Terraform Init
        working-directory: infrastructure
        run: terraform init

      - name: Terraform Plan
        working-directory: infrastructure
        run: terraform plan

      - name: Terraform Apply
        working-directory: infrastructure
        run: terraform apply -auto-approve

      - name: Get API endpoint
        id: api
        working-directory: infrastructure
        run: |
          EP=$(terraform output -raw http_api_endpoint)
          echo "endpoint=$EP" >> $GITHUB_OUTPUT

      - name: Test HTTP inference
        run: |
          curl -s -X POST "${{ steps.api.outputs.endpoint }}/infer" \
            -H "Content-Type: application/json" \
            -d '{"city":"Bogota","features":{"temp":17.14,"hum":66,"pres":1014,"wind":2.24}}' | tee response_http.json

      - name: Show response
        run: cat response_http.json